# Generated by Django 2.2.27 on 2022-08-04 09:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamesessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date announcedd')),
                ('hasBegun', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamesessions.Game')),
                ('sessiontype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamesessions.SessionType')),
            ],
            options={
                'ordering': ['date', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='gamemod',
            options={'ordering': ['game', 'name']},
        ),
        migrations.CreateModel(
            name='SessionMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamesessions.GameMod')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamesessions.Session')),
            ],
            options={
                'ordering': ['session'],
            },
        ),
    ]
