# Generated by Django 2.2.27 on 2022-08-04 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamesessions', '0002_auto_20220804_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['date', 'game', 'sessiontype', 'name']},
        ),
        migrations.AlterField(
            model_name='gamemod',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamesessions.Game'),
        ),
        migrations.AlterField(
            model_name='gamenation',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamesessions.Game'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date announced'),
        ),
        migrations.AlterField(
            model_name='session',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamesessions.Game'),
        ),
        migrations.AlterField(
            model_name='session',
            name='sessiontype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamesessions.SessionType'),
        ),
        migrations.AlterField(
            model_name='sessionmod',
            name='mod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamesessions.GameMod'),
        ),
        migrations.CreateModel(
            name='SessionPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDone', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamesessions.Session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['session', 'order', 'user'],
            },
        ),
    ]
