# Generated by Django 2.2.27 on 2022-08-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesessions', '0004_auto_20220804_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplayer',
            name='order',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='sessionplayer',
            name='savefile',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
